# Generated by Django 2.1.7 on 2019-04-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=10)),
                ('vote', models.IntegerField(default=0)),
                ('user', models.IntegerField(default=0)),
            ],
        ),
    ]
