# Generated by Django 2.1.7 on 2019-04-04 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_auto_20190404_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AlterField(
            model_name='vote',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='count.Star'),
        ),
    ]
