# Generated by Django 2.1.7 on 2019-05-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0003_auto_20190404_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote',
        ),
        migrations.AlterField(
            model_name='vote',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='count.Star'),
        ),
    ]
